name: Build and deploy slides
on:
    push:
        branches:
            - main
jobs:
    publish:
        runs-on: self-hosted
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        env:
            BUILD_TYPE: production
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 20
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            # Build the slides to /dist
            - run: pnpm build
            # Upload the built slides to the artifact store
            - uses: actions/upload-pages-artifact@v2
              with:
                path: dist
            # Deploy the slides to GitHub Pages
            - uses: actions/deploy-pages@v2
              id: deployment
