name: Build and deploy slides
on:
    push:
        branches:
            - master
jobs:
    publish:
        runs-on: self-hosted
        env:
            BUILD_TYPE: production
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 20
            - uses: pnpm/action-setup@v2
              with:
                version: 8
            - run: pnpm build-publish
